"""
routes/reports.py — Report generation and management.
"""

from flask import Blueprint, request, jsonify
from database import db, Report, SystemLog
from auth_utils import login_required

reports_bp = Blueprint('reports', __name__)


# ── POST /api/reports/ ───────────────────────────────────────────
@reports_bp.route('/', methods=['POST'])
@login_required
def create_report(current_user):
    data = request.get_json() or {}
    report = Report(
        report_name  = data.get('report_name', 'Unnamed Report'),
        generated_by = current_user.id,
    )
    db.session.add(report)
    db.session.add(SystemLog(
        log_type = 'report',
        message  = f'Report "{report.report_name}" generated by user {current_user.id}',
    ))
    db.session.commit()
    return jsonify(report.to_dict()), 201


# ── GET /api/reports/ ────────────────────────────────────────────
@reports_bp.route('/', methods=['GET'])
@login_required
def list_reports(current_user):
    reports = Report.query.order_by(Report.report_date.desc()).all()
    return jsonify([r.to_dict() for r in reports]), 200


# ── GET /api/reports/logs ────────────────────────────────────────
@reports_bp.route('/logs', methods=['GET'])
@login_required
def system_logs(current_user):
    if not current_user.is_admin:
        return jsonify({'error': 'Admin required'}), 403
    logs = SystemLog.query.order_by(SystemLog.created_at.desc()).limit(200).all()
    return jsonify([l.to_dict() for l in logs]), 200
